#!/bin/bash
#===============================================================================
# Script Name: rename_screenshots.sh
#
# Description:
#   This script batch renames screenshot files generated by the Windows 11 Snipping Tool,
#   which typically have default names like:
#     'Screenshot 2025-07-23 180209.png'
#     'Screenshot 2025-07-23 180645.png'
#     'Screenshot 2025-07-23 181052.png'
#
#   It renames all .png files in the current directory to a new format consisting of
#   a user-supplied prefix followed by a zero-padded two-digit sequential number,
#   e.g., PREFIX-01.png, PREFIX-02.png, ..., PREFIX-56.png.
#
# Usage:
#   ./rename_screenshots.sh PREFIX
#
#   where PREFIX is the desired filename prefix (e.g., "Ch3")
#
# Behavior:
#   - Processes all .png files in the current directory
#   - Sorts files alphabetically by their original filenames
#   - Renames them sequentially with the given prefix and zero-padded suffixes
#   - Safely handles filenames with spaces and special characters
#===============================================================================

if [ $# -ne 1 ]; then
  echo "Usage: $0 PREFIX"
  exit 1
fi

prefix="$1"
i=1

ls -1 *.png | sort | while IFS= read -r file; do
  new=$(printf "%s-%02d.png" "$prefix" "$i")
  mv -- "$file" "$new"
  ((i++))
done

